### ISSUE TITLE
请问楼主，这个项目是怎么创建的（关于graphite部分，这点我不懂，能否讲解一下）

### ISSUE THREAD

**Issue by WANGYANG12138** [runtangr/qidian_spider#1]
这个项目是在linux上完成的吗？graphite官网说要在linux下才能搞graphite

**Comment by runtangr** [comment]
对的，是在linux下，graphite你可以用docker 来弄，比较方便。

**Comment by WANGYANG12138** [comment]
那能不能在windows下安装使用呢

**Comment by runtangr** [comment]
我不建议这样做，如果你想这样做，可以去查资料，我没有这样做过。
